apiVersion: v1
kind: Pod
metadata:
  name: node-js-pod
  labels:
    name: node-js
spec:
  containers:
    - name: node-js-pod
      image: bitnami/apache:latest
      ports:
        - containerPort: 80
