version: "3"

services:
   redis:
     image: redis:alpine
     volumes:
       - redis_data:/data
     restart: always
   mobycounter:
     depends_on:
       - redis
     image: russmckendrick/moby-counter
     ports:
       - "8080:80"
     deploy:
       replicas: 3
       restart_policy: 
         condition: on-failure
volumes:
    redis_data: